### ISSUE TITLE
Check validity of molecules

### ISSUE THREAD

**Issue by zoumath** [Networks-Learning/nevae#2]
In your paper, you mentioned the validity of the graph is checked using RDKit.
What specific function did you use? Is it on the graph, or on the SMILES format converted from the graph?
Thanks in advance.

**Comment by bidishasamantakgp** [comment]
Hi,
First we convert the generated molecular graph into a .mol file format. Then we use Chem.MolFromMolFile() with sanitize=True, to convert it to a molecule object.  It fails if the generated mol file has invalid molecular structure. Then we convert them to smiles for calculating novelty.
