### ISSUE TITLE
Dimension problems

### ISSUE THREAD

**Issue by lxlsu** [Networks-Learning/nevae#5]
Hello, I'm trying to run the project. And I find some problems when I run the sample.py
1. model.py line: 189 ,  through the decoder, the size of the dec_out should be n * n ,but  the code final can't get the right size. so, it can't be reshape to n * n . w_edge has the same problem.
2. model.py,  sample_graph function can't work properly,  feed_dict.update gets error(ValueError: setting an array element with a sequence).    I changed it to:   feed_dict.update({self.weight_bin: weight_bins[0]})      feed_dict.update({self.edges: edges[0]}). and it works. but the decoder still has problem.
3. hope get your answer. thanks for your reading.

**Comment by bidishasamantakgp** [comment]
Hi,

Could you please run the branch node_label? We are revamping the project and will push the fix soon.
